### ISSUE TITLE
Doc update

### ISSUE THREAD

**Issue by lkursell** [qiime2/q2-phylogeny#22]
The help string for `phylogeny.methods.filter_table` indicates that the method modifies the table "in-place":

```
Call signature: phylogeny.methods.filter_table(table, tree)
Call docstring:
Filter feature table in-place against a phylogenic tree
```

This lead to some confusion, because running
```
phylogeny.methods.filter_table(table.rarified_table, tree.rooted_tree)
```
doesn't provide a `table.rarified_table.filtered_table` (not to say that it's possible for methods to chain together like that).

What does work is
```
new_table = phylogeny.methods.filter_table(table.rarified_table, tree.rooted_tree)
new_table.filtered_table
```

Can the Call docstring be updated to indicate that this is not "in place" the same way that `pandas` can filtered a dataframe in place?

**Comment by jairideout** [comment]
That is pretty misleading, thanks for reporting @lkursell!
