### ISSUE TITLE
Swap FastTree for FastTreeMP (included in bioconda installation)

### ISSUE THREAD

**Issue by jakereps** [qiime2/q2-phylogeny#35]
Currently `q2_phylogeny.fasttree` uses the `FastTree` binary, which is single threaded. `FastTree` offers a parallel version [`FastTreeMP`](http://www.microbesonline.org/fasttree/#OpenMP) that the bioconda recipe for `FastTree` installs with it (both are in the `.../envs/.../bin` folder after installing the `qiime2` core distribution.

This defaults to using all available cores (at least in my two uses of it I've seen that), but it can be modified using `export OMP_NUM_THREADS=#` as an environment variable, which Python's `subprocess.run` should know about? (I know it requires passing env variables in to `.Popen`, but `.run` should theoretically be fine [may require adding `shell=True` though]).

This could default to 1, and have a `threads` parameter or some variant of that which would just update the environment variable before calling the command.

**Comment by jairideout** [comment]
:+1: This sounds like a useful feature to get in, are you interested in working on it?

**Comment by jakereps** [comment]
Sure thing, 👍 , I could get this and the qiime2/q2-alignment/issues/31 worked up by the end of the weekend!

**Comment by jakereps** [comment]
So after looking into this a bit more I noticed this caveat:

> As of version 2.1, FastTreeMP will not give exactly the same results as FastTree because the top-hits heuristics become non-deterministic (depending on which seed is reached first) and because the star topology test is turned off. However, in practice, the results are of the same quality.

Is that an issue at all? Should it just be noted in the parameter description or something?

**Comment by gregcaporaso** [comment]
@jakereps, this shouldn't be an issue. I've used FastTreeMP a lot, and haven't noticed any issues that impact downstream conclusions (e.g., UniFrac clustering). Thanks for offering to work on this - it'll be really helpful to have this option!

**Comment by jairideout** [comment]
@gregcaporaso, related to @jakereps' question above: do you want q2-phylogeny to use `FastTree` or `FastTreeMP` when `n-threads=1`? It's unclear what `FastTreeMP` does in that case (i.e. does it use the more stable algorithm?).

**Comment by gregcaporaso** [comment]
Good question, I'm not sure what `FastTreeMP` does when `n-threads=1`. How about `FastTree` when `n-threads=1`, and `FastTreeMP` when `n-threads>1`? That'll stay consistent with how we've been using `FastTree` up until this point.
