### ISSUE TITLE
add filter-features methods

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-phylogeny#36]
**Comments**
Will support removing (or retaining) tips in a tree.

**Comment by wasade** [comment]
Should not be restricted to tips, but include unused edges/vertices in general (e.g., `TreeNode.shear`). It is also advantageous to collapse single descendent nodes, which is taken care of by `TreeNode.shear`.

**Comment by thermokarst** [comment]
Hey @gregcaporaso, can you help us out with a QIIME 1 "feature parity" use case? Thanks!

**Comment by wasade** [comment]
@thermokarst, UniFrac and PD. The extraneous edges bloat runtime as these methods scale linearly with the number of edges in the tree, and often there are a very large number of unused edges when performing these analyses. Anything performing a tree visualization will also benefit. It may also be advantageous (and not presently supported in QIIME1 AFAIK), to filter the table based on the phylogeny (e.g., dropping sOTUs which are some threshold from root or tips).

**Comment by cherman2** [comment]
Looks like this was addressed by @jwdebelius. Closing issue!
