### ISSUE TITLE
Questionable values are being added to `name` attribute 

### ISSUE THREAD

**Issue by mortonjt** [qiime2/q2-phylogeny#39]
**Bug Description**
Not sure if this is an skbio issue, but since I first noticed this problem after running the Moving Pictures qiime2 tutorial, I'll raise the issue here.

When investigating the actual `TreeNode` data structure, it looks like the `name` attribute is being populated with some float values.
```
>>> art = qiime2.Artifact.load('rooted-tree.qza')
>>> tree = art.view(TreeNode)
>>> tree.children[1].children
[<TreeNode, name: 1830c14ead81ad012f1db0e12f8ab6a4, internal node count: 0, tips count: 0>,
 <TreeNode, name: 0.739, internal node count: 756, tips count: 759>]
>>> tree.children[1].children[1].length
0.257113916
```
It looks like these aren't branch lengths, so I'm guessing that they are confidence values.

**Questions**
Wouldn't it be appropriate to assign these sorts of values to an `confidence` attribute instead of `name`?  Shouldn't `name` be reserved for unique identifiers? (i.e. taxonomy names)

**Comment by ebolyen** [comment]
Those are probably just what `fasttree` wrote in the newick file. I'm not really sure what that's supposed to represent...

**Comment by cherman2** [comment]
Closing issue since it doesn't seem to break anything downstream. Please Re-open if this is an ongoing issue.
