### ISSUE TITLE
BUG: `align_to_tree_mafft_fasttree` n_threads is inconsistent with help text

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-phylogeny#50]
[Set to a minimum of 1](https://github.com/qiime2/q2-phylogeny/blob/master/q2_phylogeny/plugin_setup.py#L354) but [help text](https://github.com/qiime2/q2-phylogeny/blob/master/q2_phylogeny/plugin_setup.py#L369) specifies that -1 uses all available jobs.

See [here](https://github.com/qiime2/q2-phylogeny/blob/master/q2_phylogeny/plugin_setup.py#L102) for proper parameter range.

**Comment by mikerobeson** [comment]
@nbokulich @thermokarst @turanoo I can fix this bit and submit a PR along with [issue 51](https://github.com/qiime2/q2-phylogeny/issues/51). Unless there is something else that needs to be fixed other than this line.

**Comment by thermokarst** [comment]
Thanks @mikerobeson! I would like @turanoo to work on this as part of his training as an Undergraduate Research Software Engineer in our lab. Thanks so much for the offer!
