### ISSUE TITLE
expose --p-partree in align-to-tree-mafft-fasttree

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-phylogeny#66]
**Improvement Description**
Expose the `partree` parameter in this pipeline. This will enable this pipeline to be used on very large sets of sequences

**Current Behavior**
partree is not exposed

**Proposed Behavior**
expose it

**References**
[forum xref](https://forum.qiime2.org/t/no-such-option-parttree/12916?u=nicholas_bokulich)

**Comment by mikerobeson** [comment]
This will also apply to the other new `align-to-tree-mafft-*` pipelines I am working on: iqtree (#63) & raxml (#65).

**Comment by mikerobeson** [comment]
I've committed an update to #65 to expose this option.  🎆

**Comment by mikerobeson** [comment]
I've put in a PR (#68) to expose this option specifically for the fasttree pipeline.

**Comment by mikerobeson** [comment]
@nbokulich This can be closed now. This option has been added to both the fasttree and raxml pipelines and merged into 2020.2.
