### ISSUE TITLE
align_to_tree_mafft_fasttree with 'auto' for n_threads only uses 1 thread with FastTreeMP

### ISSUE THREAD

**Issue by pooranis** [qiime2/q2-phylogeny#80]
**Bug Description**
If you specify _'auto'_ for the ``n_threads`` argument in the ``align_to_tree_mafft_fasttree`` function, q2-phylogeny [sets the OMP_NUM_THREADS environment variable to 0](https://github.com/qiime2/q2-phylogeny/blob/3dbcd4feae72c80214937e6a7988ab1e697c12ac/q2_phylogeny/_fasttree.py#L41).  FastTreeMP issues a warning and then uses OMP_NUM_THREADS=1.  

**Steps to reproduce the behavior**
1. Use ``n_threads='auto'`` in ``align_to_tree_mafft_fasttree`` on a machine with multiple processors.
2. Check the stderr/stdout messages from the pipeline:
```
Command: FastTreeMP -quote -nt /tmp/qiime2-archive-uwck28s2/c827dc99-ef57-4c83-abe4-42463c6c441b/data/aligned-dna-sequences.fasta

OMP: Warning #80: OMP_NUM_THREADS="0": value too small.
OMP: Info #104: OMP_NUM_THREADS value "1" will be used.
FastTree Version 2.1.10 Double precision (No SSE3), OpenMP (1 threads)
```

**Expected behavior**
The description of the _'auto'_ option in [the docs](https://docs.qiime2.org/2021.4/plugins/available/phylogeny/align-to-tree-mafft-fasttree/) say all available cores should be used, not just 1.

**Computation Environment**
- OS: Tested on macOS 10.15 with 1.4 GHz Quad-Core Intel Core i5 proc using QIIME 2 2021.4
- And Linux CentOS 7 with 16 processors using QIIME 2 2020.11

**Comments**
1. The [FastTreeMP docs](http://www.microbesonline.org/fasttree/#OpenMP) say that you can unset OMP_NUM_THREADS, and then it will use all available cores.

**Comment by thermokarst** [comment]
Thanks @pooranis!

When we first implemented this functionality (several years ago), setting `OMP_NUM_THREADS=0` in older versions of `FastTreeMP` fell-back to setting the thread count to the _max_ allowable, but it looks like this has changed in later versions of `FastTreeMP` to setting to the _min_:

![Screen Shot 2021-05-18 at 10 51 15 AM](https://user-images.githubusercontent.com/274668/118700120-28740880-b7c7-11eb-9749-59b175739499.png)

We will put this on our TODO list to fix up, thanks for the report!
